spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379

room:
  key:
    prefix: "room:"
    counter: "${room.key.prefix}counter"
    providerPostfix: ":provider"
  library:
    nameOfAddMember: "add_member_lib"
    nameOfDeleteMember: "delete_member_lib"
    functionKeyOfAddMember: "add_member"
    functionKeyOfDeleteMember: "delete_member"
  member:
    init: 1
    limit: 100

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_LOCAL_PORT}